# MATRIX MULTIPLICATION

## NORMAL METHOD

In [1]:
matrix1 =[[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[3,2,1],[6,5,4],[9,8,7]]
  
res = [[0 for x in range(3)] for y in range(3)]  
  
# explicit for loops 
for i in range(len(matrix1)): 
    for j in range(len(matrix2[0])): 
        for k in range(len(matrix2)): 
  
            # resulted matrix 
            res[i][j] += matrix1[i][k] * matrix2[k][j] 
  
print (res) 

[[42, 36, 30], [96, 81, 66], [150, 126, 102]]


## NUMPY METHOD

In [1]:
import numpy as np
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2=np.array([[3,2,1],[6,5,4],[9,8,7]])
ans=np.dot(mat1,mat2)
print(ans)

[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
